/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a dash_adaptor dash.xml
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dash_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CanReceiverAdaptor
 */

CanReceiverAdaptor::CanReceiverAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CanReceiverAdaptor::~CanReceiverAdaptor()
{
    // destructor
}

void CanReceiverAdaptor::setData(double my_speed, double my_rpm, double my_battery, const QString &my_gear)
{
    // handle method call local.CanReceiver.setData
    QMetaObject::invokeMethod(parent(), "setData", Q_ARG(double, my_speed), Q_ARG(double, my_rpm), Q_ARG(double, my_battery), Q_ARG(QString, my_gear));
}

