/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a dbus_test_adaptor.h: ../Dbus/dbus_test.xml
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUS_TEST_ADAPTOR_H
#define DBUS_TEST_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.example.CanData
 */
class CanDataAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.example.CanData")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.example.CanData\">\n"
"    <method name=\"setData\">\n"
"      <arg direction=\"in\" type=\"d\" name=\"rpm\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"speed\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CanDataAdaptor(QObject *parent);
    virtual ~CanDataAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void setData(double rpm, double speed);
Q_SIGNALS: // SIGNALS
};

#endif
