/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i dbus_test_adaptor.h -a :dbus_test_adaptor.cpp ../Dbus/dbus_test.xml
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dbus_test_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class CanDataAdaptor
 */

CanDataAdaptor::CanDataAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

CanDataAdaptor::~CanDataAdaptor()
{
    // destructor
}

void CanDataAdaptor::setData(double rpm, double speed)
{
    // handle method call com.example.CanData.setData
    QMetaObject::invokeMethod(parent(), "setData", Q_ARG(double, rpm), Q_ARG(double, speed));
}

